### GENERAL SETTINGS ###

# Site settings
title: GovWizely
description: "GovWizely helps government agencies build applications with their data. We bring modern technologies to government projects and work with our clientele to fight bureaucratic roadblocks."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/gw"
url: ""
# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#2b8275"
  primary_rgb: "33,130,171"
  secondary: "#FFFFF"
  link: "#1d7296"
  link_hover: "#2182ab"
  footer_heading: "#384452"
  footer_content: "#384452"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/company/govwizely
  - title: twitter
    url: https://twitter.com/GovWizely
  - title: github
    url: https://github.com/govwizely/


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - GovWizely, LLC
    - 10523-A Braddock Road
    - Fairfax, VA 22032, United States
email: info@govwizely.com
tel: 703.995.9913


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Erik Arnold
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: erik.jpeg
    social:
      - title: envelope #use for email address
        url: mailto:erik@govwizely.com
  - name: David Pranata
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: david.png
    social:
      - title: envelope #use for email address
        url: mailto:david@eigenpath.com
  - name: James Issacs
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: james.jpeg
    social:
      - title: envelope #use for email address
        url: mailto:james@govwizely.com
  - name: Tim Hammer
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: tim.png
    social:
      - title: envelope #use for email address
        url: mailto:tim@govwizely.com
  - name: AJ Singh
    position: Title
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: aj.png
    social:
      - title: envelope #use for email address
        url: mailto:aj@govwizely.com

# Clients information. Shown on Home and About pages.
clients:
  - name: GSA
    img: gsa.png
  - name: ITA
    img: ita.png
  - name: FTC
    img: ftc.png
  - name: SUSA
    img: susa.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "GovWizely helps government agencies build applications with their data. We bring modern technologies to government projects and work with our clientele to fight bureaucratic roadblocks."

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "GovWizely helps government agencies build applications with their data. We bring modern technologies to government projects and work with our clientele to fight bureaucratic roadblocks. Plus, we love big data, and the government, if anything, has a lot of data. The founders have all worked in Silicon Valley for years, but have since retreated back to the East Coast to try to turn a battleship."
    title: Who We Are
